# Generated by Django 2.2.9 on 2020-05-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0003_appuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('technician', 'technician'), ('expert', 'expert')], default='technician', max_length=255),
        ),
    ]
