# Generated by Django 2.2.9 on 2020-05-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='fcmid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
